config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins
  root to: "home#index"

  authenticate :admin do
    resources :products
    resources :categories
  end

  resource :cart, only: [:show, :update] do
    member do
      post :pay_with_paypal
      get  :process_paypal_payment
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @products = Product.all
  end
end

app/views/home/index.html.erb
<div class="row">
  <div class="col-md-8 offset-2">
    <div class="container">
      <div class="row">
        <% @products.each do |product| %>
          <div class="col-md-3">
            <div class="card">
              <img class="card-img-top" src="https://dummyimage.com/600x400/c7c7c7/737373&text=image" alt="<%= product.name%>"/>
              <div class="card-block">
                <h5 class="card-title"><%= product.name %></h5>
                <div class="card-text">
                  <div class="badge badge-primary"><%= product.categories.first.name %></div>
                  <div>$<%= product.price %></div>
                </div>
                <div class="row float-right">
                  <div class="col-md-12">
                    <%= form_for :cart, url: cart_path, method: :put do |f| %>
                      <%= f.hidden_field :product_id, value: product.id %>
                      <%= f.hidden_field :quantity, value: 1 %>
                      <%= f.submit "Add to cart" %>
                    <% end %>
                    <button class="btn btn-primary btn-sm">Add to cart</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>