config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins
  root to: "home#index"

  authenticate :admin do
    resources :products
    resources :categories
  end

  resource :cart, only: [:show, :update] do
    member do
      post :pay_with_paypal
      get  :process_paypal_payment
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def update
    product = params[:cart][:product_id]
    quantity = params[:cart][:quantity]

    current_order.add_product(product, quantity)

    redirect_to root_url, notice: "Product added successfuly"
  end

  def show
    @order = current_order
  end

  def pay_with_paypal
    order = Order.find(params[:cart][:order_id])

    #price must be in cents
    price = order.total * 100

    response = EXPRESS_GATEWAY.setup_purchase(price,
      ip: request.remote_ip,
      return_url: process_paypal_payment_cart_url,
      cancel_return_url: root_url,
      allow_guest_checkout: true,
      currency: "USD"
    )

    payment_method = PaymentMethod.find_by(code: "PEC")
    Payment.create(
      order_id: order.id,
      payment_method_id: payment_method.id,
      state: "processing",
      total: order.total,
      token: response.token
    )

    redirect_to EXPRESS_GATEWAY.redirect_url_for(response.token)
  end



  def process_paypal_payment
    details = EXPRESS_GATEWAY.details_for(params[:token])
    express_purchase_options =
      {
        ip: request.remote_ip,
        token: params[:token],
        payer_id: details.payer_id,
        currency: "USD"
      }

    price = details.params["order_total"].to_d * 100

    response = EXPRESS_GATEWAY.purchase(price, express_purchase_options)
    if response.success?
      payment = Payment.find_by(token: response.token)
      order = payment.order

      #update object states
      payment.state = "completed"
      order.state = "completed"

      ActiveRecord::Base.transaction do
        order.save!
        payment.save!
      end
    end
  end
end

app/views/carts/process_paypal_payment.html.erb
<div class="container">
	<div class="row text-center">
        <div class="col-sm-6 offset-3">
        <br><br> <h2 style="color:#0fad00">Success</h2>
        <p style="font-size:20px;color:#5C5C5C;">Thank you for your purchase. We have sent you an email with your details.</p>
        <a href="<%= root_url %>" class="btn btn-success">Continue Shopping</a>
    <br><br>
        </div>

	</div>
</div>

app/views/carts/show.html.erb
<div class="card">
    <div class="card-header bg-dark text-light">
        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
        <a href="<%= root_url%>" class="btn btn-outline-info btn-sm pull-right">Continue Shopping</a>
        <div class="clearfix"></div>
    </div>
    <div class="card-body">
      <% @order.order_items.includes(:product).each do |item| %>
        <div class="row">
            <div class="col-xs-2 col-md-2">
                <img class="img-responsive" src="http://placehold.it/120x80" alt="prewiew">
            </div>
            <div class="col-xs-4 col-md-6">
              <h4 class="product-name"><strong><%= item.product.name %></strong></h4><h4><small><%= item.product.description %></small></h4>
            </div>
            <div class="col-xs-6 col-md-4 row">
                <div class="col-xs-6 col-md-6 text-right" style="padding-top: 5px">
                  <h6><strong><%= item.price%> <span class="text-muted">x</span></strong></h6>
                </div>
                <div class="col-xs-4 col-md-4">
                  <%= item.quantity %>
                </div>
                <div class="col-xs-2 col-md-2">
                </div>
            </div>
        </div>
        <hr>
      <% end %>

    </div>
    <div class="card-footer">
        <a href="#" class="btn btn-success pull-right">Pay</a>
        <div class="pull-right" style="margin: 5px">
          Total: $<b><%= @order.total %></b>
          <%= form_for :cart, url: pay_with_paypal_cart_path, method: :post do |f| %>
            <%= f.hidden_field :order_id, value: @order.id %>
            <%= f.submit "Pay" %>
          <% end %>
        </div>
    </div>
</div>